dist: bionic
sudo: required

language: node_js
node_js:
  - 8
  - 10
  - 12

env:
  global:
    - HOMEBREW_LOGS=/tmp/homebrew/logs
    - HOMEBREW_TEMP=/tmp/homebrew/tmp

os:
  - linux
  - osx

addons:
  homebrew:
    packages:
      - gnu-tar
    update: true

before_install:
  - mkdir -p /tmp/homebrew/logs
  - mkdir -p /tmp/homebrew/tmp
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then ./before-install-linux.sh; fi

script:
- ./build-addons.sh

deploy:
  provider: s3
  access_key_id: AKIA43UV6GXGJCQQU75I
  secret_access_key:
    secure: VWuMOL0oAJXpVnVBMF16b6q9lr5dTZsyC+aVbbKZQyH+tZOaISyBKgA2ugcUbPc+qnQZU+COWXRvx0jS4AnCFpgVCTiXdENkGGZnusZcMt8LpP3n8eYTzyGBNLUCOl4hFRDrCvSxo3YCzvIfR/S0+VZoI2PvRvURDW+has9i0NGGZNWv3kXOz85s4aTUqHRsnXlAOIYW/V8bgBoam4vcIwrGJw9r+jVoki0MBCiCDpHtCuTwmenM7OY6/NsLJWZ0hc8nDXz6PzRsFDz2RhCzN8gSAt3vTCbALOnSnhLozW/h2RReyUBbmHjoCJMN65+W6wA/vkPnQgiHnPrmRPGXrTQdlsJtucS4liNyoLd4Fy4xaDbC0omCNlaB7aZYl3e5FJAKoh7rySaBDXKT08I6ly33HQJb463q0fsBzfgezjYTtJUAhaTKziczgmDFdD2xD9gCDj0yQu2u43eFXw252SXkYpRGnMnkbBStu7KxKF3T9901OP7rmcaGV/Cn5EMGwXsndErKQFtltiIo3IgWuqS/HRzVkiMO9YrAJxuzUMw/erC1iB3OyqiDxKtVaMddMxXUounl9vKUOgIXxeVkOHs9FzEUSMwMgTHqbljDIFPSwSWQ3ZwFXG/GBVlG7qDma4bnFP+E4UIstDDs9/IwB/MWy1yoqTMVVkajlJ54RRk=
  bucket: mozilla-gateway-addons
  region: us-west-2
  local-dir: builder
  upload-dir: builder
  acl: public_read
  skip_cleanup: true
