dist: bionic
sudo: required

language: node_js
node_js:
  - 8
  - 10
  - 12

env:
  global:
    - HOMEBREW_LOGS=/tmp/homebrew/logs
    - HOMEBREW_TEMP=/tmp/homebrew/tmp

os:
  - linux
  - osx

addons:
  homebrew:
    packages:
      - gnu-tar
    update: true

before_install:
  - mkdir -p /tmp/homebrew/logs
  - mkdir -p /tmp/homebrew/tmp
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then ./before-install-linux.sh; fi

script:
- ./build-addons.sh

deploy:
  provider: s3
  access_key_id: AKIA43UV6GXGJCQQU75I
  secret_access_key:
    secure: "C4P14gpjtOcagcAeq5/DQ6oequD6jm40QO1xp/fM3zH+8RGCaCVSCR2I3Mln8XGCmHBsb7GjGi88A245ORMOtEIOupqEQnly13BJ37zXTjLDtDmlJf4HCw1vztZyuHZfTNXV+Z6sFuETboxlmCXac2ONYYehs9SvvGcdX20CLC95IckOf6Ufg88hCLdp9kvU0xsqB9CKjGveFpTl6a/g2mdkfJ4+7quQ3APizyDisRe/H/E1o/9aPVjNNiI9MzsU5eARfQNKJfScKtSuzmhwN/32CZ9ubmbKjty6jB2Y2P0yVi9E7qTrph+YkKmJ6bMkN0LCMjivONJJi/8Ro8XN0ZKToRMj7VJT3deGDSnHP0y87x2miYOtjv+hkU87ojNYCupQqZbYC5voxjfY4HEDhnNbrTyc9R3EN0ZWgxxWl2iP1wvCeVEIGQupqPz2s1nJHR/WQcXVLPhoEhR8pxyIjnXnZ4C0W4MbU7xUPfYTdi9YrPy6C/hG3xc8ugnosH9z0suR1zp2n+TWruHRsRty2kDb90sOA6zF2sml5j8mV+CKLx6rp33MrchYsu6/L6QWqx+mTbRzU35PxaXYnu0ThsvAbWWyG8KO1PZABmD5Mf2Ilu7r5OTKBuBVXeb9QYs6B3VGT2sequPvV09gVbAzruUtw0gmtRsSewgF7v9ZJq0="
  bucket: mozilla-gateway-addons
  region: us-west-2
  local-dir: builder
  upload-dir: builder
  acl: public_read
  skip_cleanup: true
